get http://localhost:3000/test
###getAllItems
get http://localhost:3000/products?page_number=0
###getItemByCategory
get http://localhost:3000/product?category=someCategory&page_number=0
###
get http://localhost:3000/product/new-arrival?page_number=0
###
get http://localhost:3000/product/handpicked?page_number=0
####
get http://localhost:3000/product/handpicked-categories/5

####getHandpickedCategories
get http://localhost:3000/product/category/handpicked?page_number=0
####/product/category/handpicked
get http://localhost:3000/product/category/handpicked?category=someCategory&page_number=0
####limited-edition
get http://localhost:3000/product/limited-edition?page_number=0
####discount-edition
get http://localhost:3000/product/discount-edition?page_number=1
####search_value
get http://localhost:3000/product/search?search_value=some cat or product name&&page_number=1
####/product/:id"
get http://localhost:3000/product/1
####
get http://localhost:3000/product/related/1/2
####
get http://localhost:3000/product/reatings/1
####/popular
get http://localhost:3000/products/popular

///product/reatings




