#### test works
get http://localhost:3000/product/test
###getAllItems works
get http://localhost:3000/product/products?page_number=0
###done getProductsByCategory works 
get http://localhost:3000/product/product-category?category=Category1&&number_of_items=10&page_number=1
###done works 
get http://localhost:3000/product/new-arrival?page_number=1&&number_of_items=20
####works
get http://localhost:3000/product/handpicked-categories/5

####getHandpickedCategories works
get http://localhost:3000/product/category/handpicked?page_number=0
####/product/category/handpicked works
get http://localhost:3000/product/category/handpicked?category=someCategory&page_number=0
####limited-edition works
get http://localhost:3000/product/limited-edition?page_number=0
####discount-edition works
get http://localhost:3000/product/discount-edition?page_number=1
####search_value works
get http://localhost:3000/product/search?search_value=some cat or product name&&page_number=1
####works "
get http://localhost:3000/product/1
#### works
get http://localhost:3000/product/related/1/2
#### works done
get http://localhost:3000/product/ratings/6
####works 
get http://localhost:3000/product/popular





